language: ruby
rvm:
  - 2.6.3
install: gem install bundler jekyll && gem install s3_website && gem install sass && gem install jekyll-sitemap
script: bundle install && bundle exec jekyll build
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY_ID
  secret_access_key: $S3_SECRET_KEY
  skip_cleanup: true
  bucket: lavpathak.com
  region: us-west-1
